### ISSUE TITLE
stuck in menu

### ISSUE THREAD

**Issue by rafakid** [H0ppp/hop_vehcontrol#1]
When I leave the menu, sometimes it gets stuck with the mouse and nothing can be done. force quit the game and re-enter or restart the script

**Comment by H0ppp** [comment]
Hi pal, sorry for the delay, in the latest update i've added a feature where the slash key ( / ) will take the mouse/keyboard focus back to the game in case this happens again. I haven't been able to replicate this issue myself so I may have unintentionally patched it but either way hope this helps.

[Latest Release](https://github.com/H0ppp/hop_vehcontrol/releases/tag/v1.3)
